### ISSUE TITLE
Installation instructions are incomplete

### ISSUE THREAD

**Issue by ursomniac** [gthole/gedgo#6]
$ docker-machine create -d virtualbox gedgo
Creating CA: /Users/(user)/.docker/machine/certs/ca.pem
Creating client certificate: /Users/(user)/.docker/machine/certs/cert.pem
Running pre-create checks...
Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"

Apparently there are several dependencies that you don't mention.
Is there a way to install/test your software without requiring Docker + "unknown number of things"?

**Comment by gthole** [comment]
Yep - it looks like Docker has generally removed Toolbox in favor of Docker for Mac.  I can update the instructions to use that.
