### ISSUE TITLE
Tests - File Not Found

### ISSUE THREAD

**Issue by NickRance** [gthole/gedgo#9]
Hi Gedgo Team,

I tried to run the tests app but got a file not found, see console log below

Console log
====
docker-compose run app ./test.sh
Starting db    ... done
Starting redis ... done
standard_init_linux.go:190: exec user process caused "no such file or directory"

**Comment by gthole** [comment]
Ah, one of the perils of switching to Alpine images, all your `#!/bin/bash`s need to become `#!/bin/sh`s.

[Fixed.](https://github.com/gthole/gedgo/commit/a983b48162b9c9ead0b4ad35f01a3243eb074752) Thanks for the catch!
